apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blueprints.goauthentik.io
spec:
  group: goauthentik.io
  names:
    plural: blueprints
    singular: blueprint
    kind: Blueprint
    shortNames:
      - bp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: string