authentik:
  worker:
    volumeMounts:
      - name: authentik-blueprints
        mountPath: /blueprints/custom/
    volumes:
      - name: authentik-blueprints
        configMap:
          name: authentik-blueprints
      
blueprints:
  - name: test1
    content: |-
      hello
      world
  - name: test2
    content: |-
      hello
      world
      again